version: '3.7' # Versão do docker compose que será usado.

services:
  postgres:
    image: bitnami/postgresql:latest
    ports: # Redirecionamento de portas.
      - "5432:5432"
    environment: # Variaveis de ambiente.
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes: # Salva os dados em modo permanente.
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - "polls_redis_data:/bitnami/redis/data"

volumes:
  polls_pg_data:
  polls_redis_data: